### ISSUE TITLE
[iOS bootcamp] Project 1

### ISSUE THREAD

**Issue by henryou007** [henryou007/RottenTomatoesApp#1]
My app is completed. Please review @codepath

**Comment by codepathreview** [comment]
Hi Henry,

:+1: nice work. The point of this homework was to explore a simple example of a full MVC application with a RESTful API. For each point in the homework feedback checklist, I'll either confirm that you're on the right track with the implementation, or I'll provide some feedback:
- Nice code styling. The New York Times has a good summary of appropriate Objective-C coding conventions, you should take a quick look [here](https://github.com/NYTimes/objective-c-style-guide).
- Nice work with the header files. You should always try to minimize the number of properties and methods in the header files and move all private properties and methods into the class extension (the @interface block in the .m file).
- In future homework, we will cover how to implement models that can deserialize from an NSDictionary. It might be interesting to check out the Mantle project for a lightweight ORM.
- Your custom Movie cell should have a property called `movie`. In the custom setter of `movie`, you should configure the various labels and images. This decouples your custom cells from the table view controllers.
- Nice work loading the images asynchronously.
- Note that your images are stretched. You should observe the UIContentMode of the UIImageView. By default, it will stretch the image to match your dimensions, which is probably not what you want.
- Your error message should be displayed if a network request fails and hidden again if it succeeds. I see your network error message implementation and I see the image for the network error as well but your gif is missing demonstrating that. You can turn the WiFi on and off I believe but also check out this link where it shows you how to do so. 

In general, you should challenge yourself to create visually polished applications. That's where you'll find all the rough edges of the iOS framework and earn the next level of mastery.
